services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    devices:
      - /dev/dri:/dev/dri
    environment:
      - OLLAMA_VULKAN=1
      - OLLAMA_IGPU_ENABLE=1
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_KV_CACHE_TYPE=q8_0
      
      # Networking settings for local/containerized app access
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS="*" # Prevents CORS errors from browser-based local apps
    restart: unless-stopped
